#NEXUS

BEGIN TAXA;
	DIMENSIONS NTAX = 10;
	TAXLABELS
		'Bat_SARS_273_DQ648856' 'Bat_SARS_279_DQ648857' 'Bat_SARS_Rp_DQ071615' 'Bat_SARS_HKU3_DQ022305' '130_PC03_SZ13' '3_HP03E_GZ02' '15_HP03M_BJ02' '31_HP03L_Tor2' '110_PC04_PC4_136' '106_HP04_GZ0402' ;
END;

BEGIN CHARACTERS;
	DIMENSIONS NCHAR = 454;
	FORMAT
		DATATYPE = DNA
		GAP=-
		MISSING=?
	;

MATRIX
	'Bat_SARS_273_DQ648856'   ATGGATTTGTTTATGAGTATTTTCACACTTGGATCAATCACACGTCAACCAAGTAAGATTGAAAATGCTTTTCTTGCAAGTACTGTTCATGCTACTGCAACGATACCGCTACAAGCCTCATTCTCTTTCCGATGGCTTGTTATTGGCGTTGCACTTCTTGCTGTTTTTCAAAGCGCTTCCAAAGTAATTGCGCTTCATAAGAAGTGGCAGCTTGCCTTATACAAAGGCATCCAATTAGTTTGTAACTTGCTGCTACTCTTTGTGACAATTTATTCACATTTTCTACTTTTAGCTGCTGGCATTGAGGTACAATTTTTGTACATCTATGCTTTGATTTATATTCTGCAAATTTTAAGCTTTTGCAGATTTGTCATGAGATGCTGGCTTTGTTGGAAGTGCAAATCCAAGAATCCATTATTATATGATGCCAACTACTTTGTTTGCTGGCATACAT
	'Bat_SARS_279_DQ648857'   ATGGATTTGTTTATGAGCATTTTCACATTGGGAGCAATCACACGCCAACCAGCGAAAGTTGAAAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTGTTGGCGTTGCACTTCTTGCTGTTTTTCAAAGCGCTTCCAAAGTGATTGCGCTTCATAAGAGGTGGCAGCTTGCCTTGTATAAAGGCATTCAGTTTGTTTGCAATCTGCTGCTACTTTTTGTGACAATTTACTCACATCTTCTACTGTTAGCTGCTGGCATGGAGGCACAATTTTTGTACATCTATGCCCTGATTTACATTCTGCAAATCGTAAGCTTCTGCAGATTTATCATGAGGTGCTGGCTGTGCTGGAAGTGCAGATCCAAAAATCCATTACTCTATGATGCTAACTATTTCGTATGTTGGCACACCA
	'Bat_SARS_Rp_DQ071615'    ATGGATTTGTTTATGAGCATTTTCACATTAGGAGCAATCACACGTCAACCAGCCAAAATTGAAAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAGGCCTCACTCCCTTTCGGATGGCTTGTTGTTGGCGTTGCACTTCTTGCTGTTTTTCAAAGCGCTTCCAAGGTGATTGCGCTACATAAGAGGTGGCAGCTTGCCTTGCATAAAGGCATTCAGCTTGTATGCAATCTGCTGCTACTTTTTGTGACAATTTACTCACACCTTCTACTGTTAGCTGCTGGCATGGAGGCACAATTTCTGTACATCTATGCCCTGATTTATATTCTGCAAATCGTAAGTTTTTGTAGATTTATCATGAGATGCTGGCTGTGCTGGAAGTGCAGATCCAAAAATCCATTACTTTATGATGCTAACTACTTTGTATGTTGGCACACCA
	'Bat_SARS_HKU3_DQ022305'  ATGGATTTGTTTATGAGCATTTTCACATTGGGAGCAATCACGCGCAATCCAGCGAAAATTGAAAATGCTTCTCCTGCAAGTACTGTTCATGCTACTGCAACGATACCACTACAAGCCACATTCCCTTTCGGATGGCTTATTGTTGGCGTTGCACTTCTTGCTGTTTTTCAAAGCGCTTCTAAAGTAATTGCGCTTCATAGAAGGTGGCAGCTCGCCTTATATAAAGGCGTTCAACTTGTATGTAATATGCTGCTGCTTTTTGTGACAATTTACTCACACCTTCTACTTCTAGCTGCTTGCATGGAAGCACAATTCTTGTACATCTATGCCCTGATTTATATCTTGCAAATTGTAAGTTTTTGTAGATTTATCATGAGATGCTGGCTGTGCTGGAAGTGCAGATCCAAAAATCCATTACTCTATGATGCTAACTATTTTGTATGTTGGCATACTA
	'130_PC03_SZ13'           ATGGATTTGTTTATGAGAATTTTTACTCTTGGATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTAGCAATTTACTGCTGCTATTTGTTACCATCTATTCATATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCAGGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGATGCCAACTACTTTGTTTGCTGGCACACAC
	'3_HP03E_GZ02'            ATGGATTTGTTTATGAGATTTTTTACTCTTGGATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTTGCAATTTACTGCTGCTATTTGTTACCATCTATTCACATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCATGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGATGCCAACTACTTTGTTTGCTGGCACACAC
	'15_HP03M_BJ02'           ATGGATTTGTTTATGAGATTTTTTACTCTTGAATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTTGCAATTTACTGCTGCTATTTGTTACCATCTATTCACATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCATGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGATGCCAACTACTTTGTTTGCTGGCACACAC
	'31_HP03L_Tor2'           ATGGATTTGTTTATGAGATTTTTTACTCTTAGATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCCTGCAAGTACTGTTCATGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTTGCAATTTACTGCTGCTATTTGTTACCATCTATTCACATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCATGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGATGCCAACTACTTTGTTTGCTGGCACACAC
	'110_PC04_PC4_136'        ATGGATTTGTTTATGAGAATTTTTACTCTTGGATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCATGCAAGTACTGTTCGTGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTAGCAATTTACTGCTGCTATTTGTTACCATCTATTCACATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCAGGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGAAGCCAACTACTTTGTTTGCTGGCACACAC
	'106_HP04_GZ0402'         ATGGATTTGTTTATGAGAATTTTTACTCTTGGATCAATTACTGCACAGCCAGTAAAAATTGACAATGCTTCTCATGCAAGTACTGTTCGTGCTACAGCAACGATACCGCTACAAGCCTCACTCCCTTTCGGATGGCTTGTTATTGGCGTTGCATTTCTTGCTGTTTTTCAGAGCGCTACCAAAATAATTGCGCTCAATAAAAGATGGCAGCTAGCCCTTTATAAGGGCTTCCAGTTCATTAGCAATTTACTGCTGCTATTTGTTACCATCTATTCACATCTTTTGCTTGTCGCTGCAGGTATGGAGGCGCAATTTTTGTACCTCTATGCCTTGATATATTTTCTACAATGCATCAACGCAGGTAGAATTATTATGAGATGTTGGCTTTGTTGGAAGTGCAAATCCAAGAACCCATTACTTTATGAAGCCAACTACTTTGTTTGCTGGCACACAC;
END;

BEGIN HYPHY;

timer = Time (1); 

global betaP:=3.02655;
betaP:>0.05;
betaP:<85;
global betaQ:=2.92813;
betaQ:>0.05;
betaQ:<85;
global alpha:=0.0104743;
alpha:>0.01;
alpha:<100;
global AC:=0.281615;
global AT:=0.472322;
global CG:=0.105561;
global CT:=1.9029;
global GT:=0.221636;
pc.weights={
{    0.333333333333}
{    0.333333333333}
{    0.333333333333}
}
;


category pc = (3,pc.weights,MEAN,_x_^(betaP-1)*(1-_x_)^(betaQ-1)/Beta(betaP,betaQ),IBeta(_x_,betaP,betaQ),0,1,IBeta(_x_,betaP+1,betaQ)*betaP/(betaP+betaQ));
category c  = (4,pc,MEAN,GammaDist(_x_,alpha,alpha),CGammaDist(_x_,alpha,alpha),0,1e+25,CGammaDist(_x_,alpha+1,alpha));

GTR_Matrix={4,4};
GTR_Matrix[0][1]:=AC*t*c;
GTR_Matrix[0][2]:=t*c;
GTR_Matrix[0][3]:=AT*t*c;
GTR_Matrix[1][0]:=AC*t*c;
GTR_Matrix[1][2]:=CG*t*c;
GTR_Matrix[1][3]:=CT*t*c;
GTR_Matrix[2][0]:=t*c;
GTR_Matrix[2][1]:=CG*t*c;
GTR_Matrix[2][3]:=GT*t*c;
GTR_Matrix[3][0]:=AT*t*c;
GTR_Matrix[3][1]:=CT*t*c;
GTR_Matrix[3][2]:=GT*t*c;

baseFreqs={
{    0.285290507365}
{    0.227325422804}
{    0.205475995636}
{    0.281908074195}
}
;
Model GTR_Model=(GTR_Matrix,baseFreqs);

UseModel (GTR_Model);
Tree aTree=((((((Bat_SARS_273_DQ648856,((Bat_SARS_279_DQ648857,Bat_SARS_Rp_DQ071615)Node8,Bat_SARS_HKU3_DQ022305)Node7)Node5,3_HP03E_GZ02)Node4,15_HP03M_BJ02)Node3,130_PC03_SZ13)Node2,31_HP03L_Tor2)Node1,110_PC04_PC4_136,106_HP04_GZ0402);


DataSet 				ds 			= ReadDataFile(USE_NEXUS_FILE_DATA);
DataSetFilter 			aPart 		= CreateFilter(ds,1,"0-453","0-3,5,6,4,7-9");
LikelihoodFunction 		aLF 		= (aPart,aTree);
Optimize 				(res, aLF);

VERBOSITY_LEVEL = 1;
expectedLL = -1397.9096223264;;
diffLL 	   = Abs (res[1][0] - expectedLL);

timer2 = Time (1);
fprintf (stdout, "\n", aLF, "\nTest optimization took ", timer2-timer, " seconds.\n", diffLL , " difference between obtained and expected likelihood\n");


END;