import subprocess
import itertools
import sys
import os

try:
    from allpairspy import AllPairs
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "allpairspy"])
    from allpairspy import AllPairs

# Define the combinatorial parameters for dNdSRateAnalysis.bf
parameters = [
    ["Codon Model", "Nucleotide Model", "Fixed (nucleotide)", "Fixed (codon)"], # branch-lengths
    ["MG94", "MG94xHKY85", "MG94xREV", "GY94", "MG94xCustom"], # model
    ["None", "Run Custom"], # rate-variation
    ["Nonsynonymous", "Dual", "Constant"], # rate-variation-models
    ["Independent Discrete", "Bivariate Normal"], # distribution
    ["None", "Subtree"] # lineage-filter
]

# We want to skip testing rate-variation-models and distribution when rate-variation is "None"
# But allpairspy just generates combinations. We can filter invalid combinations or just let them run.
# If they are passed but not prompted, HyPhy KeywordArgument handles it safely because of the 4th argument fix!
# That's the beauty of the 4th argument fix we just did!

def run_test(params):
    bl, mod, rv, rvm, dist, lf = params
    
    cmd = [
        "hyphy", "res/TemplateBatchFiles/dNdSRateAnalysis.bf",
        "--alignment", "tests/data/bglobin.nex",
        "--use-tree", "Yes",
        "--code", "Universal",
        "--branch-lengths", bl,
        "--model", mod,
        "--rate-variation", rv,
        "--rate-variation-models", rvm,
        "--distribution", dist,
        "--initial-values", "Default",
        "--syn-classes", "2",
        "--nsyn-classes", "2",
        "--lineage-filter", lf
    ]
    
    if mod == "MG94xCustom":
        cmd.extend(["--model-designation", "010010"])
        
    if lf == "Subtree":
        cmd.extend(["--lineage-regex", ".*"])
        
    print(f"Running combination: BL={bl}, Model={mod}, RV={rv}, RVM={rvm}, Dist={dist}, LF={lf}")
    
    # We set OPTIMIZATION_PRECISION=0.1 environment variable? No, we can just let it run. Tiny dataset optimizes instantly.
    # We will capture stdout/stderr
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    
    if result.returncode != 0:
        print(f"[FAILED] Exit code {result.returncode}")
        print(f"STDERR:\n{result.stderr}")
        return False
    else:
        print("[PASSED]")
        return True

print("Generating pairwise test combinations...")
pairs = list(AllPairs(parameters))
print(f"Total test cases generated by all-pairs testing: {len(pairs)}")
print("-" * 50)

successes = 0
failures = 0

for i, p in enumerate(pairs):
    print(f"Test {i+1}/{len(pairs)}")
    if run_test(p):
        successes += 1
    else:
        failures += 1
    print("-" * 50)

print(f"Testing complete. Passed: {successes}, Failed: {failures}")
if failures > 0:
    sys.exit(1)
