name: Build and Test

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "x86-64 AVX2"
            os: ubuntu-latest
            cmake_flags: ""
          - name: "x86-64 no-AVX2"
            os: ubuntu-latest
            cmake_flags: "-DNOAVX=ON"
          - name: "ARM64"
            os: ubuntu-latest
            cmake_flags: ""
            arch: "aarch64"

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v2

    - name: Build binary
      run: |
        if [ "${{ matrix.arch }}" == "aarch64" ]; then
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws arm64v8/ubuntu:20.04 bash -c "apt-get update && apt-get install -y cmake make g++ && cmake . ${{ matrix.cmake_flags }} && make"
        else
          cmake . ${{ matrix.cmake_flags }}
          make
        fi

    - name: Run tests
      run: |
        if [ "${{ matrix.arch }}" == "aarch64" ]; then
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws arm64v8/ubuntu:20.04 bash -c "apt-get update && apt-get install -y cmake make g++ && cmake . ${{ matrix.cmake_flags }} && make && make test"
        else
          make test
        fi
